image: mcr.microsoft.com/dotnet/sdk:7.0

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - dotnet restore
    - dotnet build --configuration Release

test:
  stage: test
  script:
    - dotnet test --no-build

deploy:
  stage: deploy
  script:
    - dotnet publish --configuration Release
    - # add your deployment commands here
  environment:
    name: production
    url: https://example.com
